force-app/main/default/objects/Zudoc_Folder__c/Zudoc_Folder__c.object-meta.xml
<CustomObject>
    <label>Zudoc Folder</label>
    <nameField>
        <label>Zudoc Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zudoc Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zudoc_Folder__c/fields/Zudoc_Parent_Folder__c.field-meta.xml
<CustomField>
    <fullName>Zudoc_Parent_Folder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zudoc Parent Folder</label>
    <referenceTo>Zudoc_Folder__c</referenceTo>
    <relationshipLabel>Zudoc Folders</relationshipLabel>
    <relationshipName>Zudoc_Child_Folders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FolderController.cls
public with sharing class FolderController {
  @AuraEnabled(cacheable=true scope='global')
  public static Map<Id, Zudoc_Folder__c> getFolderRecords(){
    List<Zudoc_Folder__c> folderList = [
          SELECT
            Id,
            Name,
            Zudoc_Parent_Folder__c,
            Zudoc_Parent_Folder__r.Name,
            (SELECT Id, Name FROM Zudoc_Child_Folders__r)
          FROM Zudoc_Folder__c
        ];
    Map<Id, Zudoc_Folder__c> folderMap = new Map<Id, Zudoc_Folder__c>(folderList);
    return folderMap;
  }

  @AuraEnabled
  public static Zudoc_Folder__c submitNewFolder(String folderName, Id parentFolder){
    Zudoc_Folder__c newFolder = new Zudoc_Folder__c();
    newFolder.Name = folderName;
    newFolder.Zudoc_Parent_Folder__c = parentFolder;

    insert newFolder;
    return newFolder;
  }
}